from __future__ import annotations

import os
import uuid
from typing import Optional, Dict, Any, Set

import pandas as pd
import streamlit as st
from supabase import create_client, Client

from auth_helper import require_admin
from lib.ui_header import render_header


def _get_secret(name: str, default=None, required: bool = False) -> Optional[str]:
    if hasattr(st, "secrets") and name in st.secrets:
        val = st.secrets[name]
    else:
        val = os.environ.get(name, default)
    if required and (val is None or str(val).strip() == ""):
        st.error(f"Missing required secret: {name}")
        st.stop()
    return val


SUPABASE_URL = _get_secret("SUPABASE_URL", required=True)
SUPABASE_ANON_KEY = _get_secret("SUPABASE_ANON_KEY", required=True)
sb: Client = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)

if st.session_state.get("sb_access_token") and st.session_state.get("sb_refresh_token"):
    try:
        sb.auth.set_session(
            access_token=st.session_state["sb_access_token"],
            refresh_token=st.session_state["sb_refresh_token"],
        )
    except Exception as e:
        st.warning(f"Could not attach Supabase session. ({e})")


user, session, user_id = require_admin()
if not user:
    st.stop()


render_header("Admin: Sound Techs", emoji="🎛️")
st.caption("Search, edit, or add sound tech records. Does not delete records.")


def _table_columns(table: str) -> Set[str]:
    try:
        rows = sb.table(table).select("*").limit(1).execute().data or []
        return set(rows[0].keys()) if rows else set()
    except Exception:
        return set()


def _filter_to_schema(table: str, data: Dict[str, Any]) -> Dict[str, Any]:
    cols = _table_columns(table)
    if not cols:
        return data
    return {k: v for k, v in data.items() if k in cols}


def _valid_uuid(value: Any) -> bool:
    if value is None:
        return False
    try:
        if isinstance(value, uuid.UUID):
            return True
        if isinstance(value, str) and value.strip():
            uuid.UUID(value.strip())
            return True
    except (ValueError, TypeError):
        return False
    return False


@st.cache_data(ttl=30)
def _load_soundtechs() -> pd.DataFrame:
    try:
        resp = sb.table("sound_techs").select("*").order("display_name").execute()
        return pd.DataFrame(resp.data or [])
    except Exception:
        return pd.DataFrame()


df = _load_soundtechs()

mode = st.radio("Mode", ["Edit Existing", "Add New"], horizontal=True)

selected_id = None
selected_row: Dict[str, Any] = {}

if mode == "Edit Existing":
    if df.empty:
        st.info("No sound techs found; switch to Add New to create one.")
    else:
        # Build readable labels: prefer display_name, then first+last, then email, then id
        choices = []
        for _, r in df.iterrows():
            label = r.get("display_name")
            if not label:
                fn = (r.get("first_name") or "")
                ln = (r.get("last_name") or "")
                name_parts = " ".join(p for p in (fn.strip(), ln.strip()) if p).strip()
                label = name_parts if name_parts else (r.get("email") or "")
            display_label = label or r.get("id")
            choices.append(f"{display_label} | {r.get('id')}")
        sel = st.selectbox("Choose Sound Tech", choices)
        if sel:
            # Extract id from choice (last part after '|')
            sel_id = sel.split('|')[-1].strip()
            if _valid_uuid(sel_id):
                rows = df[df['id'] == sel_id]
                if not rows.empty:
                    selected_row = rows.iloc[0].to_dict()
                    selected_id = sel_id
                else:
                    st.error("Selected sound tech record could not be found in the current list.")
            else:
                st.error("Selected sound tech ID is not a valid UUID.")

st.markdown("---")

with st.form("soundtech_form"):
    if selected_row:
        # Display name is computed by DB trigger; show read-only for reference
        display_name = st.text_input("Display Name (computed)", value=selected_row.get('display_name') or "", disabled=True)
        first_name = st.text_input("First Name", value=selected_row.get('first_name') or "")
        last_name = st.text_input("Last Name", value=selected_row.get('last_name') or "")
        company = st.text_input("Company", value=selected_row.get('company') or "")
        phone = st.text_input("Phone", value=selected_row.get('phone') or "")
        email = st.text_input("Email", value=selected_row.get('email') or "")
        active_default = bool(selected_row.get('active')) if 'active' in selected_row else True
        active = st.checkbox("Active", value=active_default)
    else:
        # For new records, display_name will be generated by DB trigger from first/last
        display_name = st.text_input("Display Name (computed)", value="", disabled=True, placeholder="Computed from first/last by DB trigger")
        first_name = st.text_input("First Name")
        last_name = st.text_input("Last Name")
        company = st.text_input("Company")
        phone = st.text_input("Phone")
        email = st.text_input("Email")
        active = st.checkbox("Active", value=True)

    submitted = st.form_submit_button("Save")

    if submitted:
        # Require at least a first or last name; display_name is computed server-side
        if not (first_name or last_name):
            st.error("Please enter at least a first or last name.")
        else:
            payload: Dict[str, Any] = {
                "first_name": first_name.strip() or None,
                "last_name": last_name.strip() or None,
                "company": company.strip() or None,
                "phone": phone.strip() or None,
                "email": email.strip() or None,
            }
            if "active" in _table_columns("sound_techs"):
                payload["active"] = bool(active)

            payload = _filter_to_schema("sound_techs", payload)
            if not payload:
                st.error("No writable fields were found for sound_techs.")
            else:
                try:
                    if selected_id:
                        if not _valid_uuid(selected_id):
                            st.error("Selected id is not a valid UUID; update cannot proceed.")
                        else:
                            # If deactivating, warn if assigned to gigs (do not block)
                            if payload.get("active") is False:
                                try:
                                    rows_assigned = (
                                        sb.table("gigs").select("id").eq("sound_tech_id", selected_id).execute().data or []
                                    )
                                    cnt = len(rows_assigned)
                                    if cnt:
                                        st.warning(f"This sound tech is assigned to {cnt} gig(s). Deactivating will not remove past assignments.")
                                except Exception:
                                    pass

                            # Update existing
                            update_resp = sb.table("sound_techs").update(payload).eq("id", selected_id).execute()
                            update_data = update_resp.data or []
                            update_error = getattr(update_resp, 'error', None)

                            if update_error or not update_data:
                                st.error(f"Update failed: {update_error or 'no rows updated (data=[]).'}")
                            else:
                                st.success("Sound tech updated.")

                            # Immediately re-query the saved row from source of truth
                            query_resp = sb.table("sound_techs").select("*").eq("id", selected_id).single().execute()
                            query_data = getattr(query_resp, 'data', None)
                            query_error = getattr(query_resp, 'error', None)

                            if query_error:
                                st.error(f"Re-query failed: {query_error}")
                            elif query_data:
                                selected_row = query_data
                            else:
                                st.warning("Updated row could not be loaded after save.")

                            # Refresh cache after a successful update attempt
                            try:
                                _load_soundtechs.clear()
                            except Exception:
                                try:
                                    st.cache_data.clear()
                                except Exception:
                                    pass
                            df = _load_soundtechs()
                    else:
                        resp = sb.table("sound_techs").insert(payload).execute()
                        inserted = resp.data or []
                        resp_error = getattr(resp, 'error', None)
                        resp_meta = getattr(resp, 'status_code', None)
                        # Refresh list
                        try:
                            _load_soundtechs.clear()
                        except Exception:
                            try:
                                st.cache_data.clear()
                            except Exception:
                                pass
                        df = _load_soundtechs()
                        if resp_error:
                            st.error(f"Insert failed: {resp_error}")
                        elif inserted:
                            st.success("Sound tech added successfully.")
                        else:
                            st.success("Sound tech add request completed.")
                except Exception as e:
                    st.error(f"Could not save sound tech: {e}")

st.markdown("---")
st.caption("Note: this file may be gitignored; use `git add -f` to include it in commits after testing.")
